// COPYRIGHT (C) HARRY CLARK 2025
// A LIGHTWEIGHT IMPLEMENTATION OF COMMON UTILITIES 

#include <noodle/error.hh>
#include <fmt/core.h>

using namespace noodle::err;

// THE FOLLOWING IS A BASIC TEST DESIGNED TO PROPERLY TEST OUT
// ALL OF THE MACROS AGAINST THEIR TEMPLATED COUNTERPARTS

// THIS DOESNT DO ANYTHING OTHER THAN PROVIDING VALIDITY 
// FOR HOW THE MACROS CAN BE USED ELSEWHERE

int main(void)
{
    NOODLE_PRINT("HARRY CLARK - NOODLE (COMMON C++ UTILITES)\n");

    NOODLE_STD_ERROR ERROR1 = NOODLE_ERROR_CTX("RESOURCE ERROR - THROW STD ERROR", 
                    ERROR_CATEGORY::RES_ERR, ERROR_SEVERITY::STD_ERROR);

    fmt::print("{} CODE: {}\n", ERROR1.MSG, ERROR1.CODE);

    NOODLE_STD_ERROR ERROR2 = NOODLE_ERROR_FMT(ERROR_CATEGORY::RUNTIME_ERR, 
                    ERROR_SEVERITY::CRITICAL, 
                    "FILE: '{}' ERROR: {}", "NOODLE.TXT", "NOT FOUND");
                    
    fmt::print("{}\n", ERROR2.MSG);

    fmt::print("TRACE {}\n", NOODLE_FMT("RETURN VALUE: {}", 42));
    
    return 0;
}
