// COPYRIGHT (C) HARRY CLARK 2025
// A LIGHTWEIGHT IMPLEMENTATION OF COMMON UTILITIES 

#include <noodle/error.hh>
#include <fmt/core.h>

using namespace noodle::err;

// THE FOLLOWING IS A BASIC TEST DESIGNED TO PROPERLY TEST OUT
// ALL OF THE MACROS AGAINST THEIR TEMPLATED COUNTERPARTS

// THIS DOESNT DO ANYTHING OTHER THAN PROVIDING VALIDITY 
// FOR HOW THE MACROS CAN BE USED ELSEWHERE

int main(void)
{
    NOODLE_PRINT_BASIC("HARRY CLARK - NOODLE (COMMON C++ UTILITES)\n\n");

    NOODLE_ERROR_PRINT(ERROR_CATEGORY::RES_ERR, ERROR_SEVERITY::STD_ERROR, 
                      "SOME FILE WAS NOT FOUND - OOPSIE");
    
    NOODLE_ERROR_PRINT(ERROR_CATEGORY::RUNTIME_ERR, ERROR_SEVERITY::CRITICAL, 
                      "'{}' {}", "EVIL_NOODLE.EXE", "NOT FOUND");

    NOODLE_WARNING("USE THIS FOR GENERAL WARNING CATCHES");
    NOODLE_INFO("NOODLE FROM GORILLAZ");
    
    return 0;
}
